<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Ad p ORDER BY p.name ASC'
            )
            ->getResult();
    }

    public function findAllFrontPage()
    {
        $query = $this->createQueryBuilder('Ad')
            ->orderBy('Ad.id', 'DESC')
            ->getQuery()
            ->setMaxResults(18);
        return $query->getResult();
    }
}
