<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findRootCategories(){
        $query = $this->createQueryBuilder('Category')
            ->where('Category.parent is NULL')
            ->orderBy('Category.id', 'ASC')
            ->getQuery();
        return $query->getResult();
    }
}
